server:
  port: 8081

# 配置freemarker
spring:
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存,freemarker的热部署需要配置cache: false。
    cache: false
    # 设置ftl文件路径
    template-loader-path: classpath:/templates
    request-context-attribute: request
    check-template-location: true